[package]
name = "partial-deser"
version = "0.1.0"
edition = "2021"
description = "Deserialize with Serde from partial JSON and more"

[features]
default = ["serde_json", "tracing"]
serde_json = ["dep:serde_json", "dep:rand"]
unstable = []

[dependencies]
insta = { version = "1.42.0", features = ["ron"] }
rand = { version = "0.8", optional = true }
serde = "1.0.215"
serde_json = { version = "1.0.133", optional = true}
static_assertions = "1.1.0"
tap = "1.0.1"
thiserror = "2.0.3"
tracing = { version = "0.1", optional = true }

[dev-dependencies]
indexmap = { version = "2.7.0", features = ["serde"] }
itertools = "0.13.0"
serde = { version = "1", features = ["derive"]}
serde_json = { version = "1"}
tracing-subscriber = "0.3"

[[example]]
name = "ex1"
required-features = ["tracing", "serde_json"]
