[package]
name = "partial-deser"
version = "0.1.0"
edition = "2021"
description = "Deserialize with Serde from partial JSON and more"

[features]
default = ["serde_json", "tracing"]
unstable = []

[dependencies]
# derive_builder = "0.20.2"
rand = "0.8"
serde = "1.0.215"
serde_json = { version = "1.0.133", optional = true}
static_assertions = "1.1.0"
tap = "1.0.1"
thiserror = "2.0.3"
tracing = { version = "0.1", optional = true }

[dev-dependencies]
tracing-subscriber = "0.3"